### PR TITLE
Hungarian Translation

### PR DESCRIPTION
**Pull request by ovari**
Please advise if there are more places to change to enable the `hu` locale.

Please advise when there are new strings to translate.

Thank you

### CODE REVIEW

**Comment by rares45** [comment]
Remove the app name translation from your file, because it's untranslatable and it gives annoying warnings.
And could you merge the commits into a single one called "Hungarian Translation"?

**Comment by ovari** [comment]
> Remove the app name translation from your file, because it's untranslatable and it gives annoying warnings.
Done.

> And could you merge the commits into a single one called "Hungarian Translation"?
Don't know how to merge the commits into a single one. Using Changed the title.

Can you accept merge request and change anything else that is require?

Thank you

**Comment by ovari** [comment]
@slowscript can you please advise when a new version with the Hungarian translations will be available on F-Droid and Google Play? Thank you

**Comment by slowscript** [comment]
Unfortunately I can't tell you that. There will be a new version when we have enough changes that would justify releasing one.

**Comment by ovari** [comment]
Have you heard of the [agile](https://adtmag.com/articles/2011/01/14/how-facebook-does-agile.aspx) programming methodology?

Surely having a completed new locale would justify releasing a new version!? You should also include the updates to the German language https://github.com/slowscript/warpinator-android/pull/29 at the same time.

Having a new locale also encourages translators to translate your App into other languages. For example, if a small language like Hungarian is available in your App, translators of more popular languages might think to provide you with translations.

When this issue was created https://play.google.com/store/apps/details?id=slowscript.warpinator showed `Installs: 500+`. It now shows `Installs: 1,000+`. We are trying to help you grow your installs after the wonderful promotion by Clem on the Linux Mint blog (That is how we found out about your App). It would be good to push new releases out as soon as your App gets new translations.

When an application is in a new locale more users of that language can start using it. The sooner they start using it, the sooner word of mouth can work.

Please release a new version with the Hungarian translations.

Thank you

**Comment by slowscript** [comment]
I don't want to release two versions right after another, especially since it sometimes takes Google a few days to review them. I would have a new release ready but the previous one still would not be published in the Play store. I'm currently trying to solve #23. What I'm trying to do is easy and I should have it done by evening today. If it works, I will publish a new release with that fix and translations tomorrow. If not, I will fix some trivial crashes I see in the Play Console and release it a day after. Is this OK?

**Comment by slowscript** [comment]
Thanks! You should get 1.2 soon. I just put it on slow rollout since it contained a major change and I wanted to be able to catch the bugs it could introduce before it goes out to everybody. Just changed the rollout to 100% today but most people should have already got it on Saturday.

**Pull request merged**
